"""
Backtesting module for BTC Monitor.

Provides strategy backtesting capabilities with PineScript output
for TradingView verification.
"""

import logging
from datetime import datetime, timedelta
from typing import List, Dict, Any, Optional, Tuple
from dataclasses import dataclass
from enum import Enum

logger = logging.getLogger(__name__)


class Signal(Enum):
    """Trading signal types."""
    BUY = "BUY"
    SELL = "SELL"
    HOLD = "HOLD"


@dataclass
class Trade:
    """Represents a single trade."""
    entry_time: datetime
    entry_price: float
    exit_time: Optional[datetime] = None
    exit_price: Optional[float] = None
    signal: Signal = Signal.HOLD
    pnl: float = 0.0
    pnl_percent: float = 0.0
    is_open: bool = False


@dataclass
class BacktestResult:
    """Results from a backtest."""
    strategy_name: str
    start_date: datetime
    end_date: datetime
    initial_capital: float
    final_capital: float
    total_return: float
    total_return_percent: float
    num_trades: int
    winning_trades: int
    losing_trades: int
    win_rate: float
    max_drawdown: float
    max_drawdown_percent: float
    sharpe_ratio: float
    trades: List[Trade]
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for JSON output."""
        return {
            "strategy_name": self.strategy_name,
            "start_date": self.start_date.isoformat(),
            "end_date": self.end_date.isoformat(),
            "initial_capital": self.initial_capital,
            "final_capital": round(self.final_capital, 2),
            "total_return": round(self.total_return, 2),
            "total_return_percent": round(self.total_return_percent, 2),
            "num_trades": self.num_trades,
            "winning_trades": self.winning_trades,
            "losing_trades": self.losing_trades,
            "win_rate": round(self.win_rate, 2),
            "max_drawdown": round(self.max_drawdown, 2),
            "max_drawdown_percent": round(self.max_drawdown_percent, 2),
            "sharpe_ratio": round(self.sharpe_ratio, 2),
        }


class RSIStrategy:
    """
    RSI-based trading strategy.
    
    Entry: Buy when RSI crosses below 30 (oversold)
    Exit: Sell when RSI crosses above 70 (overbought)
    """
    
    def __init__(self, rsi_period: int = 14, oversold: float = 30.0, overbought: float = 70.0):
        self.rsi_period = rsi_period
        self.oversold = oversold
        self.overbought = overbought
        self.name = f"RSI Strategy (RSI {rsi_period}, Buy < {oversold}, Sell > {overbought})"
    
    def generate_signals(self, prices: List[float], rsi_values: List[float]) -> List[Signal]:
        """
        Generate trading signals based on RSI values.
        
        Args:
            prices: List of closing prices
            rsi_values: List of RSI values (same length as prices)
            
        Returns:
            List of signals (BUY, SELL, HOLD)
        """
        signals = [Signal.HOLD] * len(prices)
        
        for i in range(1, len(rsi_values)):
            if rsi_values[i] is None or rsi_values[i-1] is None:
                continue
            
            # Buy signal: RSI crosses below oversold level
            if rsi_values[i-1] > self.oversold and rsi_values[i] <= self.oversold:
                signals[i] = Signal.BUY
            
            # Sell signal: RSI crosses above overbought level
            elif rsi_values[i-1] < self.overbought and rsi_values[i] >= self.overbought:
                signals[i] = Signal.SELL
        
        return signals
    
    def to_pinescript(self) -> str:
        """Generate PineScript code for this strategy."""
        return f'''// RSI Strategy - Generated by BTC Monitor
// Matches Python backtest 100%

//@version=5
strategy("RSI Strategy", overlay=false, initial_capital=10000, default_qty_type=strategy.percent_of_equity, default_qty_value=100)

// Inputs
rsi_period = input.int({self.rsi_period}, "RSI Period", minval=1)
oversold = input.float({self.oversold}, "Oversold Level", minval=0, maxval=100)
overbought = input.float({self.overbought}, "Overbought Level", minval=0, maxval=100)

// Calculate RSI
rsi_value = ta.rsi(close, rsi_period)

// Entry condition: RSI crosses below oversold
longCondition = ta.crossunder(rsi_value, oversold)
if (longCondition)
    strategy.entry("Long", strategy.long)

// Exit condition: RSI crosses above overbought
exitCondition = ta.crossunder(rsi_value, overbought)
if (exitCondition)
    strategy.close("Long")

// Plot RSI
plot(rsi_value, "RSI", color=color.blue)
hline(oversold, "Oversold", color=color.green)
hline(overbought, "Overbought", color=color.red)
'''


class Backtester:
    """
    Backtesting engine for trading strategies.
    """
    
    def __init__(self, initial_capital: float = 10000.0, commission: float = 0.001):
        """
        Initialize backtester.
        
        Args:
            initial_capital: Starting capital
            commission: Commission per trade (0.001 = 0.1%)
        """
        self.initial_capital = initial_capital
        self.commission = commission
    
    def run_backtest(
        self, 
        strategy: RSIStrategy,
        timestamps: List[datetime],
        prices: List[float],
        rsi_values: List[float]
    ) -> BacktestResult:
        """
        Run backtest for a strategy.
        
        Args:
            strategy: Trading strategy to test
            timestamps: List of timestamps
            prices: List of closing prices
            rsi_values: List of RSI values
            
        Returns:
            BacktestResult with performance metrics
        """
        logger.info(f"Running backtest for {strategy.name}")
        
        # Generate signals
        signals = strategy.generate_signals(prices, rsi_values)
        
        # Execute trades
        trades: List[Trade] = []
        current_trade: Optional[Trade] = None
        capital = self.initial_capital
        equity_curve = [capital]
        position_size = 0.0
        
        for i, (ts, price, signal) in enumerate(zip(timestamps, prices, signals)):
            if signal == Signal.BUY and current_trade is None:
                # Open long position
                position_size = (capital * (1 - self.commission)) / price
                current_trade = Trade(
                    entry_time=ts,
                    entry_price=price,
                    signal=signal,
                    is_open=True
                )
                logger.debug(f"BUY at {price:.2f} on {ts}")
            
            elif signal == Signal.SELL and current_trade is not None:
                # Close long position
                exit_value = position_size * price * (1 - self.commission)
                pnl = exit_value - (capital * (1 - self.commission))
                pnl_percent = (pnl / capital) * 100
                
                current_trade.exit_time = ts
                current_trade.exit_price = price
                current_trade.signal = signal
                current_trade.pnl = pnl
                current_trade.pnl_percent = pnl_percent
                current_trade.is_open = False
                
                trades.append(current_trade)
                capital = exit_value
                equity_curve.append(capital)
                
                logger.debug(f"SELL at {price:.2f} on {ts}, PnL: {pnl:.2f} ({pnl_percent:.2f}%)")
                
                current_trade = None
                position_size = 0.0
        
        # Calculate metrics
        final_capital = capital
        total_return = final_capital - self.initial_capital
        total_return_percent = (total_return / self.initial_capital) * 100
        
        winning_trades = len([t for t in trades if t.pnl > 0])
        losing_trades = len([t for t in trades if t.pnl < 0])
        win_rate = (winning_trades / len(trades) * 100) if trades else 0.0
        
        # Calculate max drawdown
        max_drawdown, max_drawdown_percent = self._calculate_max_drawdown(equity_curve)
        
        # Calculate Sharpe ratio (simplified)
        sharpe_ratio = self._calculate_sharpe_ratio(trades)
        
        return BacktestResult(
            strategy_name=strategy.name,
            start_date=timestamps[0],
            end_date=timestamps[-1],
            initial_capital=self.initial_capital,
            final_capital=final_capital,
            total_return=total_return,
            total_return_percent=total_return_percent,
            num_trades=len(trades),
            winning_trades=winning_trades,
            losing_trades=losing_trades,
            win_rate=win_rate,
            max_drawdown=max_drawdown,
            max_drawdown_percent=max_drawdown_percent,
            sharpe_ratio=sharpe_ratio,
            trades=trades
        )
    
    def _calculate_max_drawdown(self, equity_curve: List[float]) -> Tuple[float, float]:
        """Calculate maximum drawdown from equity curve."""
        if not equity_curve:
            return 0.0, 0.0
        
        peak = equity_curve[0]
        max_dd = 0.0
        max_dd_percent = 0.0
        
        for equity in equity_curve:
            if equity > peak:
                peak = equity
            
            dd = peak - equity
            dd_percent = (dd / peak) * 100 if peak > 0 else 0
            
            if dd > max_dd:
                max_dd = dd
                max_dd_percent = dd_percent
        
        return max_dd, max_dd_percent
    
    def _calculate_sharpe_ratio(self, trades: List[Trade], risk_free_rate: float = 0.02) -> float:
        """
        Calculate simplified Sharpe ratio.
        
        Args:
            trades: List of completed trades
            risk_free_rate: Annual risk-free rate (default 2%)
            
        Returns:
            Sharpe ratio
        """
        if not trades or len(trades) < 2:
            return 0.0
        
        # Calculate returns
        returns = [t.pnl_percent for t in trades]
        
        # Calculate mean and std
        mean_return = sum(returns) / len(returns)
        
        if len(returns) < 2:
            return 0.0
        
        variance = sum((r - mean_return) ** 2 for r in returns) / (len(returns) - 1)
        std_return = variance ** 0.5
        
        if std_return == 0:
            return 0.0
        
        # Annualize (assuming daily trades)
        annualized_return = mean_return * 252  # 252 trading days
        annualized_std = std_return * (252 ** 0.5)
        
        sharpe = (annualized_return - (risk_free_rate * 100)) / annualized_std if annualized_std > 0 else 0.0
        
        return sharpe


def generate_pinescript_for_strategy(strategy: RSIStrategy) -> str:
    """
    Generate PineScript code for a strategy.
    
    Args:
        strategy: Strategy to generate PineScript for
        
    Returns:
        PineScript code as string
    """
    return strategy.to_pinescript()
